service: csv-parser
frameworkVersion: '2'

custom:
  bucket: ab-serverless-test-23032001-1201

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    QUEUE_URL:  
      "Fn::ImportValue": "ToDoQueue"
    REGION: ${self:provider.region}
  iamRoleStatements:
    - ${file(../../serverless.common.yml):lambdaPolicyXRay}
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:*:*:ToDoQueue"

plugins:
  - serverless-bundle

functions:
  transform-file-s3-to-sqs:
    handler: src/handler.transformFile
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
